#!/bin/bash

set -euo pipefail

mountdir="mounts/$(basename "${MEMORY_CARD_DEVICE}")"
./sd-exec passwd
./sd-exec bash -c < ~/.ssh/id_rsa.pub '
passwd -d alarm
passwd -l alarm
umask 077
mkdir -p ~/.ssh
exec cat > ~/.ssh/authorized_keys'
./sd-exec su alarm -c < ~/.ssh/id_rsa.pub '
umask 077
mkdir -p ~/.ssh
exec cat > ~/.ssh/authorized_keys'
