#!/bin/bash

set -euo pipefail

./sd-umount
sudo fdisk -w always -W always "${MEMORY_CARD_DEVICE}" <<EOF
o
n
p
1

+200M
t
c
n
p
2

+4G
n
p
3


w
EOF
sudo mkfs.vfat "${MEMORY_CARD_DEVICE}"p1
sudo mkfs.ext4 -F "${MEMORY_CARD_DEVICE}"p2
sudo mkfs.f2fs -f -l mutable "${MEMORY_CARD_DEVICE}"p3
mountdir="mounts/$(basename "${MEMORY_CARD_DEVICE}")"
sudo mount "${MEMORY_CARD_DEVICE}"p2 "${mountdir}"
sudo mkdir -p "${mountdir}"/boot "${mountdir}"/mnt/mutable
sudo mount "${MEMORY_CARD_DEVICE}"p1 "${mountdir}"/boot
sudo mount "${MEMORY_CARD_DEVICE}"p3 "${mountdir}"/mnt/mutable
sudo chmod 1777 "${mountdir}"/mnt/mutable
container="$(podman create ${IMAGE:-localhost/archlinuxarm/rpi-armv7:latest})"
trap 'podman rm "${container}" > /dev/null' EXIT
podman export "${container}" | sudo tar x -C "${mountdir}"

./sd-exec bash -c '
systemd-machine-id-setup
ssh-keygen -A
mkdir /mnt/mutable/timesync
chown systemd-timesync:systemd-timesync /mnt/mutable/timesync
'

[[ -f ~/.ssh/id_rsa.pub ]] || exit
./sd-exec bash -c < ~/.ssh/id_rsa.pub '
passwd -d root
passwd -l root
passwd -d alarm
passwd -l alarm
umask 077
mkdir -p ~/.ssh
exec cat > ~/.ssh/authorized_keys'
./sd-exec su alarm -c < ~/.ssh/id_rsa.pub '
umask 077
mkdir -p ~/.ssh
exec cat > ~/.ssh/authorized_keys'
