#!/bin/bash

set -euo pipefail

./sd-umount
mountdir="mounts/$(basename "${MEMORY_CARD_DEVICE}")"
mkdir -p "${mountdir}"
sudo mount "${MEMORY_CARD_DEVICE}"*2 "${mountdir}"
sudo mount "${MEMORY_CARD_DEVICE}"*1 "${mountdir}"/boot
sudo mount "${MEMORY_CARD_DEVICE}"*3 "${mountdir}"/mnt/mutable

echo "$(realpath "${mountdir}")"
