#!/bin/bash

set -euo pipefail

mountdir="$(realpath mounts/$(basename "${MEMORY_CARD_DEVICE}"))"

if findmnt "${mountdir}"/mnt/host > /dev/null; then
  sudo umount "${mountdir}"/mnt/host
  sudo rm -rf "${mountdir}"/mnt/host
fi

if findmnt "${MEMORY_CARD_DEVICE}"p3 > /dev/null; then
  sudo umount "${MEMORY_CARD_DEVICE}"p3
fi
if findmnt "${MEMORY_CARD_DEVICE}"p1 > /dev/null; then
  sudo umount "${MEMORY_CARD_DEVICE}"p1
fi
if findmnt "${MEMORY_CARD_DEVICE}"p2 > /dev/null; then
  sudo umount "${MEMORY_CARD_DEVICE}"p2
fi
