w /sys/class/leds/ACT/trigger - - - - none
w /sys/class/leds/ACT/brightness - - - - 0
w /sys/class/leds/PWR/trigger - - - - none
w /sys/class/leds/PWR/brightness - - - - 0
w /sys/class/leds/mmc0*/trigger - - - - none
w /sys/class/leds/mmc0*/brightness - - - - 0
w /sys/class/leds/*:lan/trigger - - - - none
w /sys/class/leds/*:lan/brightness - - - - 0
